name: 'Create Release'
description: 'Creates a release from a push with a tag reference'
inputs:
  token:
    description: 'Secret Github Token'
    required: true
outputs:
  response:
    description: 'The response from the successful create release api call'
runs:
  using: 'node12'
  main: 'dist/index.js'
